name: "action-docker-test"
description: "Run a test file in a Docker container"
inputs:
  test-command:
    description: "Command to execute to run tests"
    required: true
  dockerfile-path:
    description: "Path to the directory with the Dockerfile"
    required: false
    default: "."
  build-command:
    description: "Full command to build the image"
    required: false
    default: "docker build"
outputs:
  success:
    description: "Whether the test was successful"
    value: ${{ steps.set-output.outputs.success }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate unique name
      run: echo "TAG=$(uuidgen)" >> "$GITHUB_ENV"
    - name: Build image
      run: ${{ inputs.build-command }} -t ${TAG} ${{ inputs.dockerfile-path }}
      shell: bash
    - name: Start container
      run: docker run -dit -v $(pwd):$(pwd) -w $(pwd) --name ${TAG} ${TAG}
      shell: bash
    - name: Run tests
      run: docker exec ${TAG} ${{inputs.test-command}}
      shell: bash
    - name: Set output
      id: set-output
      run: echo "success=true" >> $GITHUB_OUTPUT
      shell: bash
