name: "action-docker-test"
description: "Run a test file in a Docker container"
inputs:
  tests-path:
    description: "Path to test file"
    required: true
outputs:
  success:
    description: "Whether the test was successful"
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: echo Path to tests= ${{inputs.tests-path}}
      shell: bash
    - name: Build image
      run: docker build -t image .
      shell: bash
    - name: Start container
      run: docker run -dit --name image image
      shell: bash
    - name: Run tests
      run: docker exec image node --version
      shell: bash
