name: Release Action
permissions: {}
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    outputs:
      success: ${{steps.dockertest.outputs.success}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Test
        uses: ./
        id: dockertest
        with:
          test-command: "sh ./test.sh"
          dockerfile-path: "."
      - name: Output
        run: echo ${{ steps.dockertest.outputs.success}}
        shell: bash
  release:
    runs-on: ubuntu-latest
    name: Release Action
    needs: test
    if: ${{ needs.test.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Release Action
        uses: outoforbitdev/action-semantic-release@v1.6.2
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
      - name: Summarize Versions
        env:
          LAST_VERSION: ${{ steps.semantic-release.outputs.last-version }}
          NEXT_VERSION: ${{ steps.semantic-release.outputs.next-version }}
          VERSION_RELEASED: >-
            ${{ steps.semantic-release.outputs.version-released}}
        run: >-
          echo "### Version Summaries" >> $GITHUB_STEP_SUMMARY;
          echo "* Last version - $LAST_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Next version - $NEXT_VERSION" >> $GITHUB_STEP_SUMMARY;
          echo "* Version released - $VERSION_RELEASED" >> $GITHUB_STEP_SUMMARY
