name: Test Action
run-name: Testing
permissions: {}
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - alpha
      - beta
      - dev
      - staging
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    name: Test Action
    outputs:
      versionReleased: ${{steps.dockertest.outputs.success}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Test
        uses: ./
        id: dockertest
        with:
          tests-path: "./tests.sh"
          