name: Test Action
permissions: {}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - alpha
      - beta
      - dev
      - staging
jobs:
  dockertest:
    runs-on: ubuntu-latest
    name: Test Action
    outputs:
      success: ${{steps.dockertest.outputs.success}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Test
        uses: ./
        id: dockertest
        with:
          test-command: "sh ./test.sh"
          dockerfile-path: "."
      - name: Output
        run: echo ${{ steps.dockertest.outputs.success}}
        shell: bash
